"""mod follow methods of user table

Revision ID: 011ec1899437
Revises: 3662127ab597
Create Date: 2022-12-31 21:38:26.857822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011ec1899437'
down_revision = '3662127ab597'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
