"""removed messages from contacts table

Revision ID: 011f804ccb8d
Revises: 28c127bc7d38
Create Date: 2022-11-12 22:02:50.035650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '011f804ccb8d'
down_revision = '28c127bc7d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
