"""mod is_following method in user table

Revision ID: 029e0b21dbbd
Revises: 80487a9f086d
Create Date: 2022-12-30 13:25:40.603911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029e0b21dbbd'
down_revision = '80487a9f086d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
