"""renamed is_followed method and added is_following method to user table

Revision ID: 07069d87dde9
Revises: 5f0b9438e44e
Create Date: 2022-12-31 21:14:38.479232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07069d87dde9'
down_revision = '5f0b9438e44e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
