"""changed chat default from private to p2p

Revision ID: 13731d3842f7
Revises: 6b7e7460e9af
Create Date: 2022-11-18 22:52:07.785013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13731d3842f7'
down_revision = '6b7e7460e9af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
