"""added like methods to post table

Revision ID: 1375eb8ce855
Revises: 011ec1899437
Create Date: 2023-01-01 09:50:07.278657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1375eb8ce855'
down_revision = '011ec1899437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
