"""added ec private and public key fields

Revision ID: 15ddeec4435b
Revises: 1375eb8ce855
Create Date: 2023-01-05 19:41:52.829485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ddeec4435b'
down_revision = '1375eb8ce855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ec_privkey', sa.String(), nullable=True))
    op.add_column('users', sa.Column('ec_pub_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ec_pub_key')
    op.drop_column('users', 'ec_privkey')
    # ### end Alembic commands ###
