"""corrected spelling mistake in is_following method in user table

Revision ID: 182a462b3029
Revises: a3421ea1be4b
Create Date: 2022-12-31 05:37:30.290152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182a462b3029'
down_revision = 'a3421ea1be4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
