"""used indexing on posts strip_date time argument

Revision ID: 1ab3b164cf76
Revises: 68a609b15783
Create Date: 2022-12-31 18:44:52.642839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab3b164cf76'
down_revision = '68a609b15783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
