"""corrected chate date in repData method of chat table

Revision ID: 1b904846910c
Revises: 5ce9f5307731
Create Date: 2022-11-14 08:41:19.125834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b904846910c'
down_revision = '5ce9f5307731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
