"""created pages and follows tables

Revision ID: 1d693e3b25b0
Revises: 948ca69439c4
Create Date: 2022-11-30 11:32:57.114933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d693e3b25b0'
down_revision = '948ca69439c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
