"""removed contact id and to from messages table

Revision ID: 28c127bc7d38
Revises: 638bef63ddab
Create Date: 2022-11-12 21:56:22.610220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28c127bc7d38'
down_revision = '638bef63ddab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_contact_id_fkey', 'messages', type_='foreignkey')
    op.drop_column('messages', 'contact_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('messages_contact_id_fkey', 'messages', 'contacts', ['contact_id'], ['contact_id'])
    # ### end Alembic commands ###
