"""created config field for user table

Revision ID: 2c309e565543
Revises: 3d1eea3c955c
Create Date: 2022-12-27 06:34:23.915686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c309e565543'
down_revision = '3d1eea3c955c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'config')
    # ### end Alembic commands ###
