"""removed nanoseconds from posts strip_date time argument

Revision ID: 2f04dac56405
Revises: c36dfdb3e386
Create Date: 2022-12-31 18:39:24.113737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f04dac56405'
down_revision = 'c36dfdb3e386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
