"""corrected variable error in follows methoduser table

Revision ID: 3662127ab597
Revises: 5f5a14a20e31
Create Date: 2022-12-31 21:21:48.868610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3662127ab597'
down_revision = '5f5a14a20e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
