"""created self-referential many to many relationship for following

Revision ID: 3d1eea3c955c
Revises: 7381e6ce4cf0
Create Date: 2022-12-26 22:59:35.724417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d1eea3c955c'
down_revision = '7381e6ce4cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
