"""added date to chat table

Revision ID: 3d882daf7636
Revises: 011f804ccb8d
Create Date: 2022-11-13 07:15:10.381475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d882daf7636'
down_revision = '011f804ccb8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
