"""removed replace method from posts strip_date time argument

Revision ID: 3febf1882fd7
Revises: ce95417fcbdf
Create Date: 2022-12-31 18:52:32.988373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3febf1882fd7'
down_revision = 'ce95417fcbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
