"""mod is_following methods in user table

Revision ID: 440f497b574d
Revises: 7d60ba80c394
Create Date: 2022-12-28 07:29:57.074837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440f497b574d'
down_revision = '7d60ba80c394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
