"""corrected notation error in genkeys method

Revision ID: 46e38f28ae7f
Revises: 3d801264153e
Create Date: 2023-01-06 19:39:45.267847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46e38f28ae7f'
down_revision = '3d801264153e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
