"""used isoformat on posts strip_date time argument

Revision ID: 4bf35206c4c6
Revises: 1ab3b164cf76
Create Date: 2022-12-31 18:49:42.688593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf35206c4c6'
down_revision = '1ab3b164cf76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
