"""mod genkey method and added loadkey methods

Revision ID: 4d89437166db
Revises: 6c5eed10b0f9
Create Date: 2023-01-06 19:11:53.455590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d89437166db'
down_revision = '6c5eed10b0f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
