"""added date formatting nethod to posts table

Revision ID: 50cc245c83a6
Revises: a1c317c8556f
Create Date: 2022-12-31 18:21:17.159083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50cc245c83a6'
down_revision = 'a1c317c8556f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
