"""mod loadkey method

Revision ID: 540401b50dfd
Revises: 4d89437166db
Create Date: 2023-01-06 19:13:55.763803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540401b50dfd'
down_revision = '4d89437166db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
