"""modified chat date column table

Revision ID: 54b989509713
Revises: 3d882daf7636
Create Date: 2022-11-13 07:19:48.123350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b989509713'
down_revision = '3d882daf7636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('chat_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'chat_date')
    # ### end Alembic commands ###
