"""added session commit to follow methods in user table

Revision ID: 5b2f2009cb0d
Revises: ff5d69e0ce1e
Create Date: 2022-12-31 06:43:31.239867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2f2009cb0d'
down_revision = 'ff5d69e0ce1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
