"""added repData method to chat table

Revision ID: 5ce9f5307731
Revises: f1c82f81de45
Create Date: 2022-11-14 08:19:51.145803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ce9f5307731'
down_revision = 'f1c82f81de45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
