"""created spaces table

Revision ID: 5d70f63ac153
Revises: 1d693e3b25b0
Create Date: 2022-12-14 15:48:23.311648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d70f63ac153'
down_revision = '1d693e3b25b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
