"""updated user to users in chats table

Revision ID: 5e608f99538a
Revises: 570a447dc38d
Create Date: 2022-11-11 06:58:59.485588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e608f99538a'
down_revision = '570a447dc38d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
