"""mod is_following method in user table 4th_time

Revision ID: 5e9fcdb48dc0
Revises: 9b22ab8f8fc5
Create Date: 2022-12-31 04:56:28.925972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9fcdb48dc0'
down_revision = '9b22ab8f8fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
