"""removed strip_date method from post table

Revision ID: 5f0b9438e44e
Revises: b66964102db8
Create Date: 2022-12-31 20:34:53.513999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f0b9438e44e'
down_revision = 'b66964102db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
