"""renamed method variables in user table

Revision ID: 5f5a14a20e31
Revises: 07069d87dde9
Create Date: 2022-12-31 21:16:48.354885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5a14a20e31'
down_revision = '07069d87dde9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
