"""corrected posts strip_date argument type to time str error

Revision ID: 650a8b28c62d
Revises: 7520a4c63a8e
Create Date: 2022-12-31 18:27:12.693971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650a8b28c62d'
down_revision = '7520a4c63a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
