"""undid last change to posts strip_date time argument

Revision ID: 68a609b15783
Revises: 2f04dac56405
Create Date: 2022-12-31 18:40:43.213577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68a609b15783'
down_revision = '2f04dac56405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
