"""added measure to prevent self follow in is_following method in user table

Revision ID: 69263a153034
Revises: 182a462b3029
Create Date: 2022-12-31 05:42:15.269901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69263a153034'
down_revision = '182a462b3029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
