"""created chat media table

Revision ID: 6b7e7460e9af
Revises: 1b904846910c
Create Date: 2022-11-16 07:31:08.456675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7e7460e9af'
down_revision = '1b904846910c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
