"""mod keys and key methods

Revision ID: 6c5eed10b0f9
Revises: b9da3601726c
Create Date: 2023-01-06 19:01:24.068028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c5eed10b0f9'
down_revision = 'b9da3601726c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('priv_key', sa.String(), nullable=True))
    op.add_column('users', sa.Column('pub_key', sa.String(), nullable=True))
    op.drop_column('users', 'ec_privkey')
    op.drop_column('users', 'ec_pub_key')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ec_pub_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('ec_privkey', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'pub_key')
    op.drop_column('users', 'priv_key')
    # ### end Alembic commands ###
