"""added measure to prevent self follow in follow and unfollow methods of user table

Revision ID: 7094079b1310
Revises: 69263a153034
Create Date: 2022-12-31 05:46:07.101726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7094079b1310'
down_revision = '69263a153034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
