"""renamed follows table to page follow

Revision ID: 7381e6ce4cf0
Revises: 7c1fdc74e585
Create Date: 2022-12-26 22:44:25.259867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7381e6ce4cf0'
down_revision = '7c1fdc74e585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
