"""changed posts strip_date argument type to time str

Revision ID: 7520a4c63a8e
Revises: a6d3ef4f6dd5
Create Date: 2022-12-31 18:24:40.863947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7520a4c63a8e'
down_revision = 'a6d3ef4f6dd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
