"""removed seconds from posts strip_date time argument

Revision ID: 76d596a5a8d8
Revises: 650a8b28c62d
Create Date: 2022-12-31 18:33:45.261426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76d596a5a8d8'
down_revision = '650a8b28c62d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
