"""added follow, unfollow and is_following methods to user table

Revision ID: 7d60ba80c394
Revises: 9e51b2e5f4ce
Create Date: 2022-12-28 06:28:42.513435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d60ba80c394'
down_revision = '9e51b2e5f4ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
