"""added replies to comments table

Revision ID: 80487a9f086d
Revises: ba625b55b9a4
Create Date: 2022-12-28 20:31:03.349941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80487a9f086d'
down_revision = 'ba625b55b9a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'comments', ['parent_id'], ['comm_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###
