"""added first and last name fields

Revision ID: 8153f58d27b6
Revises: 5d70f63ac153
Create Date: 2022-12-25 15:35:29.485533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8153f58d27b6'
down_revision = '5d70f63ac153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
