"""corrected date column field name error

Revision ID: 948ca69439c4
Revises: fb828201386c
Create Date: 2022-11-30 10:02:13.304529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '948ca69439c4'
down_revision = 'fb828201386c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.drop_column('pages', 'date_cteated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('date_cteated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('pages', 'date_created')
    # ### end Alembic commands ###
