"""mod is_following method in user table 3rd_time

Revision ID: 9b22ab8f8fc5
Revises: c03bdd208b65
Create Date: 2022-12-31 04:34:41.073477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b22ab8f8fc5'
down_revision = 'c03bdd208b65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
