"""renamed followers assocuation table and followers fields in user table

Revision ID: 9e51b2e5f4ce
Revises: f9d0271a0465
Create Date: 2022-12-28 05:39:58.389978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e51b2e5f4ce'
down_revision = 'f9d0271a0465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('followed_id', sa.Integer(), nullable=False))
    op.drop_constraint('follows_following_id_fkey', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['followed_id'], ['user_id'])
    op.drop_column('follows', 'following_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('following_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key('follows_following_id_fkey', 'follows', 'users', ['following_id'], ['user_id'])
    op.drop_column('follows', 'followed_id')
    # ### end Alembic commands ###
