"""added return to follow method of user table

Revision ID: a1c317c8556f
Revises: b9a2bff9c6af
Create Date: 2022-12-31 12:46:44.170931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c317c8556f'
down_revision = 'b9a2bff9c6af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
