"""mod is_following, follow and unfollow methods in user table 5th_time

Revision ID: a3421ea1be4b
Revises: 5e9fcdb48dc0
Create Date: 2022-12-31 05:35:33.589478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3421ea1be4b'
down_revision = '5e9fcdb48dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
