"""added lastchat method to chat table

Revision ID: a696e7a7d931
Revises: 54b989509713
Create Date: 2022-11-14 07:03:51.381177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a696e7a7d931'
down_revision = '54b989509713'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
