"""changed ppsts strip_date argument type to str

Revision ID: a6d3ef4f6dd5
Revises: 50cc245c83a6
Create Date: 2022-12-31 18:23:44.949880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d3ef4f6dd5'
down_revision = '50cc245c83a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
