"""readded replace method to posts strip_date time argument

Revision ID: b66964102db8
Revises: 3febf1882fd7
Create Date: 2022-12-31 18:53:43.982111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66964102db8'
down_revision = '3febf1882fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
