"""added followed posts method to user table

Revision ID: b9a2bff9c6af
Revises: 5b2f2009cb0d
Create Date: 2022-12-31 07:42:27.557801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9a2bff9c6af'
down_revision = '5b2f2009cb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
