"""mod gen private key method

Revision ID: b9da3601726c
Revises: 15ddeec4435b
Create Date: 2023-01-05 19:45:07.331595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9da3601726c'
down_revision = '15ddeec4435b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
