"""muted follows methods of user table

Revision ID: ba625b55b9a4
Revises: 440f497b574d
Create Date: 2022-12-28 10:24:20.020180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba625b55b9a4'
down_revision = '440f497b574d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
