"""mod is_following method in user table 2nd_time

Revision ID: c03bdd208b65
Revises: 029e0b21dbbd
Create Date: 2022-12-31 04:33:36.800806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03bdd208b65'
down_revision = '029e0b21dbbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
