"""removed microseconds from posts strip_date time argument

Revision ID: c36dfdb3e386
Revises: 76d596a5a8d8
Create Date: 2022-12-31 18:34:50.577213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36dfdb3e386'
down_revision = '76d596a5a8d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
