"""used isoformat calling on posts strip_date time argument

Revision ID: ce95417fcbdf
Revises: 4bf35206c4c6
Create Date: 2022-12-31 18:51:11.383156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce95417fcbdf'
down_revision = '4bf35206c4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
