"""Corrected mapping error in chats and messahes table

Revision ID: ec05c6e75eed
Revises: 012f8c95b166
Create Date: 2022-11-10 08:49:38.626946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec05c6e75eed'
down_revision = '012f8c95b166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
