"""updated chats field in users table

Revision ID: ed7d38cd6c49
Revises: 5e608f99538a
Create Date: 2022-11-11 07:08:41.643673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7d38cd6c49'
down_revision = '5e608f99538a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
