"""added self to lastchat method to chat table

Revision ID: f1c82f81de45
Revises: a696e7a7d931
Create Date: 2022-11-14 07:16:17.519048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c82f81de45'
down_revision = 'a696e7a7d931'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
