"""mod loadkeys, encrypt method

Revision ID: f2ed4364a1b5
Revises: 540401b50dfd
Create Date: 2023-01-06 19:32:18.722934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ed4364a1b5'
down_revision = '540401b50dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
