"""added get feed method to user table

Revision ID: f9d0271a0465
Revises: 2c309e565543
Create Date: 2022-12-27 13:33:10.400991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d0271a0465'
down_revision = '2c309e565543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
