"""reapplied correction to spelling mistake in is_following method in user table

Revision ID: ff5d69e0ce1e
Revises: 7094079b1310
Create Date: 2022-12-31 05:47:55.212703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff5d69e0ce1e'
down_revision = '7094079b1310'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
